# Generated by Django 3.1.7 on 2021-04-28 02:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitepizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morada', models.TextField(max_length=50, null=True)),
                ('telemovel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('image', models.ImageField(upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('nrPorta', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('metPagamento', models.CharField(max_length=25)),
                ('codigoPostal1', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('codigoPostal2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitepizza.pedido')),
            ],
        ),
    ]
