# Generated by Django 3.1.7 on 2021-04-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0002_checkout_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
