# Generated by Django 3.1.7 on 2021-04-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0006_checkout_rua'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
