# Generated by Django 3.1.7 on 2021-04-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0008_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
