# Generated by Django 3.1.7 on 2021-04-28 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0010_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telemovel',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
