# Generated by Django 3.1.7 on 2021-04-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0012_auto_20210428_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtopedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
