# Generated by Django 3.1.7 on 2021-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0015_auto_20210430_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtopedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
