# Generated by Django 3.1.7 on 2021-04-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0022_checkout_metentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='metPagamento',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
