# Generated by Django 3.1.7 on 2021-04-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0023_auto_20210430_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='codigoPostal1',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='codigoPostal2',
        ),
    ]
