# Generated by Django 3.1.7 on 2021-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepizza', '0024_auto_20210430_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valorPedido',
            field=models.FloatField(default=0),
        ),
    ]
